version: '3.4'

services:
  #ZOOKEEPER
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:3.9.0'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  #KAFKA
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:3.1.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true


  # POSTGRES FOR PROFILE
  sportlize.pgsql.profile:
    image: postgres:latest
    container_name: db-sportlize-pgsql-profile
    environment:
      POSTGRES_DB: SportLizeProfile
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 8002:5432

  # PROFILE
  sportlize.profile.api:
    container_name: api-sportlize-profile
    image: ${DOCKER_REGISTRY-}sportlizeprofile
    build:
      context: .
      dockerfile: src/SportLize.Profile.Api/Dockerfile
    environment:
      - DB_HOST=sportlize.pgsql.profile
      - DB_NAME=SportLizeProfile
      - DB_SA_PASSWORD=postgres

  # POSTGRES FOR HOME
  sportlize.pgsql.home:
    image: postgres:latest
    container_name: db-sportlize-pgsql-home
    environment:
      POSTGRES_DB: SportLizeHome
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 8003:5432

  # HOME
  sportlize.home.api:
    container_name: api-sportlize-home
    image: ${DOCKER_REGISTRY-}sportlizehome
    build:
      context: .
      dockerfile: src/SportLize.Home.Api/Dockerfile
    environment: 
      - DB_HOST=sportlize.pgsql.home
      - DB_NAME=SportLizeHome
      - DB_SA_PASSWORD=postgres

  # POSTGRES FOR GROUP
  sportlize.pgsql.group:
    image: postgres:latest
    container_name: db-sportlize-pgsql-group
    environment:
      POSTGRES_DB: SportLizeGroup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 8004:5432

  # GROUP
  sportlize.group.api:
    container_name: api-sportlize-group
    image: ${DOCKER_REGISTRY-}sportlizegroup
    build:
      context: .
      dockerfile: src/SportLize.Group.Api/Dockerfile
    environment: 
      - DB_HOST=sportlize.pgsql.group
      - DB_NAME=SportLizeGroup
      - DB_SA_PASSWORD=postgres

  # FRONTEND
  sportlize.front.razor:
    image: ${DOCKER_REGISTRY-}sportlizefront
    build:
      context: .
      dockerfile: src/SportLize.Front.Razor/Dockerfile
